In [25]:
import numpy as np
#1. Crear un array con los números del 1 al 10
array_10=np.array([1,2,3,4,5,6,7,8,9,10])

In [26]:
#2. Imprimir el array
print(array_10)

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
#3. Mostrar el valor máximo y mínimo
print(array_10.max())
print(array_10.min())

10
1


In [28]:
#4. Crear un arreglo de 5 ceros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [29]:
#5. Crear un arreglo de 5 unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
#6. Crear la siguiente matriz:
matrix=np.array([[1,2,3],[4,5,6]])

In [31]:
#7. Mostrar la matriz
print(matrix)

[[1 2 3]
 [4 5 6]]


In [32]:
#8. Mostrar la dimensión con shape
print(matrix.shape)

(2, 3)
